[package]
name = "lualdap-rs"
version = "0.1.0"
authors = ["Lukas Stevens"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ldap3 = "0.9"
mlua = { version = "0.6", features = ["lua54", "vendored", "module"] }
